version: '3.1'
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}
    depends_on:
      - db
      - pgadmin
    ports:
      - "${WEB_PORT}:8069"
      - "${WEBSOCKET_PORT}:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/etc/odoo
      - ./addons:/mnt/extra-addons
    entrypoint: "/usr/bin/odoo -c /etc/odoo/.env --dev all -i base"
  db:
    container_name: ${db_host}
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_USER=${db_user}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${PGADMIN_HOST}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:${PGADMIN_DATA}
volumes:
  odoo-db-data:
  pgadmin-data:
  odoo-web-data:
